"""
P5.3 -- Real, measured KV-cache rebuild ("reactivation") cost.

P5.3's circuit breaker must degrade speculative decoding to plain
target-only autoregressive generation when batch load is high, and
periodically re-probe whether conditions allow turning it back on. This
script measures the one real, unavoidable cost of that re-activation:

  - While speculative decoding is DISABLED, the target model keeps
    generating tokens on its own (exactly like p5_kv_cache_target_only.py)
    -- its cache grows normally the whole time, so disabling costs nothing
    and there is nothing to "rebuild" on the target side.
  - The DRAFT model, however, is not being called at all while disabled,
    so its cache stops growing and falls behind by however many tokens
    the target produced alone. Before the draft model can propose
    candidates again, it must first be fed all of those missed tokens in
    one forward pass, to bring its cache back in sync with the true
    current position -- exactly the _forward_step() catch-up mechanism
    already used (and already verified correct) inside
    speculative_decoding_step_cached's full-acceptance branch.

That one catch-up forward pass -- as a function of how many tokens were
missed (i.e. how long the circuit breaker stayed disabled) -- IS the "KV
cache rebuild cost" project_plan_v9.md requires measuring, to compare
against Nightjar's reported 17.87-102.03ms range (real numbers, not an
assumption that switching is free, unlike BanditSpec's approach per the
plan's own critique).

This script does NOT implement the circuit breaker's decision logic
(when to disable, when to re-probe) -- that is a separate, pure
control-flow piece with no real model calls to measure, built next. This
script measures the one piece of that design that has to be an honest,
real number.

REVISION (same day, first run was too noisy to trust): the first version
of this script warmed up MPS only once, at a single input shape, before
timing all six gap sizes. Standard deviations came back larger than the
means for several gap sizes (gap=5: 31.15ms +/- 33.37ms), and the numbers
were not monotonic in gap size (gap=5 and gap=10 both measured HIGHER
than gap=20) -- both signs of a measurement artifact, not a real finding.
Suspected cause: MPS/Metal likely compiles a kernel graph per distinct
input shape the first time it's seen, so a gap size's first-ever call
pays a one-time compile cost indistinguishable, in the old script, from
steady-state cost. Fixed by warming up EACH gap size once (untimed)
before timing it. Also switched the "missed token" generation (target
model producing tokens while disabled) to use its own KV cache -- this
was previously an uncached, quadratic-cost loop; it doesn't affect the
timed measurement (never inside the timed block) but was needlessly slow
for the larger gap sizes. Runs per gap size raised 5 -> 15, and every
individual run's raw time is now printed (not just the aggregate) so an
outlier is visible rather than hidden inside a mean+std pair.
"""

import sys
import statistics
import time
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

import torch

from src.model_loader import DRAFT_MODEL_NAME, TARGET_MODEL_NAME, load_model_and_tokenizer
from src.speculative_decode_kv import _forward_step, _cache_len

PROMPT = (
    "Write a detailed, step-by-step explanation of how a hash table works, "
    "including how collisions are handled."
)
# How many tokens might have been generated by target-alone while the
# circuit breaker was disabled, before a re-probe decides to re-enable.
GAP_SIZES = [1, 5, 10, 20, 50, 100]
N_RUNS = 15
BASE_SEED = 800


def sync():
    if torch.backends.mps.is_available():
        torch.mps.synchronize()


@torch.no_grad()
def build_primed_draft_cache(draft_model, prompt_ids):
    """Simulate speculative decoding having run normally for a while: the
    draft model's cache is fully caught up to the end of the prompt."""
    _, cache = _forward_step(draft_model, prompt_ids, None)
    return cache


@torch.no_grad()
def generate_missed_tokens(target_model, prompt_ids, gap, generator, device):
    """What "circuit breaker disabled" looks like: target alone, WITH its
    own cache (matches p5_kv_cache_target_only.py -- there is no rebuild
    cost on this side, see module docstring). Not timed; only exists to
    produce realistic tokens for the draft model to catch up on."""
    cache = None
    feed = prompt_ids
    missed = []
    for _ in range(gap):
        dists, cache = _forward_step(target_model, feed, cache)
        probs = dists[-1]
        tok = torch.multinomial(probs.cpu(), 1, generator=generator).to(device)
        missed.append(tok.item())
        feed = tok.unsqueeze(0)
    return torch.tensor([missed], device=device)


@torch.no_grad()
def measure_rebuild_cost(draft_model, draft_cache, missed_tokens):
    """The actual re-activation catch-up: feed all `missed_tokens` (the
    tokens target generated alone while disabled) through the draft model
    in ONE forward pass, timed precisely."""
    sync()
    t0 = time.perf_counter()
    _, new_cache = _forward_step(draft_model, missed_tokens, draft_cache)
    sync()
    elapsed = time.perf_counter() - t0
    return elapsed, new_cache


def main():
    print("=" * 70)
    print("Specter -- P5.3 circuit breaker: real KV-cache rebuild cost")
    print("(Nightjar reference range: 17.87-102.03ms)")
    print("=" * 70)

    print("\nLoading Draft...")
    draft_model, tokenizer = load_model_and_tokenizer(DRAFT_MODEL_NAME)
    print("\nLoading Target (needed only to generate realistic 'missed' tokens)...")
    target_model, _ = load_model_and_tokenizer(TARGET_MODEL_NAME)

    device = next(draft_model.parameters()).device
    prompt_ids = tokenizer(PROMPT, return_tensors="pt")["input_ids"].to(device)

    print(f"\nPrompt length: {prompt_ids.shape[1]} tokens")
    print(f"Gap sizes to test (tokens missed while disabled): {GAP_SIZES}")
    print(f"Runs per gap size: {N_RUNS}\n")

    results = {}
    for gap in GAP_SIZES:
        # Per-gap warm-up (untimed): the first call at THIS input shape may
        # pay a one-time MPS kernel-compile cost -- pay it here, not inside
        # a timed measurement.
        warm_cache = build_primed_draft_cache(draft_model, prompt_ids)
        warm_missed = torch.zeros((1, gap), dtype=torch.long, device=device)
        _ = measure_rebuild_cost(draft_model, warm_cache, warm_missed)

        gen = torch.manual_seed(BASE_SEED + gap)
        times = []
        print(f"--- gap={gap} ---")
        for run in range(N_RUNS):
            # Fresh draft cache primed on the prompt, every run -- so each
            # measurement is independent and not polluted by a growing
            # cache from a previous run's leftover state.
            draft_cache = build_primed_draft_cache(draft_model, prompt_ids)
            draft_start_len = _cache_len(draft_cache)

            missed_tensor = generate_missed_tokens(target_model, prompt_ids, gap, gen, device)

            elapsed, rebuilt_cache = measure_rebuild_cost(draft_model, draft_cache, missed_tensor)
            times.append(elapsed)
            print(f"  run {run+1:2d}: {elapsed*1000:7.2f}ms")

            # Sanity check: the rebuild must actually advance the cache by
            # exactly `gap` positions -- catching a broken measurement
            # (e.g. an accidental no-op) rather than trusting the timer alone.
            assert _cache_len(rebuilt_cache) == draft_start_len + gap, (
                f"rebuild did not advance the cache correctly: "
                f"expected {draft_start_len + gap}, got {_cache_len(rebuilt_cache)}"
            )

        mean_ms = statistics.mean(times) * 1000
        median_ms = statistics.median(times) * 1000
        std_ms = (statistics.stdev(times) * 1000) if len(times) > 1 else 0.0
        results[gap] = (mean_ms, median_ms, std_ms)
        print(f"  -> mean={mean_ms:7.2f}ms  median={median_ms:7.2f}ms  std={std_ms:5.2f}ms\n")

    print("=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"{'gap':>6s} {'mean':>10s} {'median':>10s} {'std':>10s}")
    for gap, (mean_ms, median_ms, std_ms) in results.items():
        print(f"{gap:6d} {mean_ms:9.2f}ms {median_ms:9.2f}ms {std_ms:9.2f}ms")

    print("\nComparison to Nightjar's reported range (17.87-102.03ms), using the median")
    print("(more robust than the mean if any single run is a shape/JIT outlier):")
    for gap, (mean_ms, median_ms, std_ms) in results.items():
        in_range = 17.87 <= median_ms <= 102.03
        verdict = "within range" if in_range else ("below range" if median_ms < 17.87 else "above range")
        print(f"  gap={gap:4d}: median={median_ms:7.2f}ms -- {verdict}")
    print("=" * 70)


if __name__ == "__main__":
    main()
